frase = str(input('Digite uma frase qualquer: ')).strip().upper()
print('A frase digitada foi {}'.format(frase))
print('Quantas vezes o A aparece: {}'.format(frase.count('A')))
print('Primeira posição dele: {}'.format(frase.find('A')+1))
print('A última posição dele: {}'.format(frase.rfind('A')+1))