print('-'*30)
print('    E X P R E S S   W O R L D    ')
print('-'*30)
print('Oi, Tudo bem ?')
nome = str(input('Então digite seu nome: ')).title().strip()
destino = str(input('Qual é o seu destino: ')).upper().strip()
Quilometro = float(input('Quantos km é a viagem: '))
if Quilometro <= 200:
    print('-'*30)
    print('EXPRESS WORLD')
    print('-'*30)
    print('Ola, {} Seja bem vindo!'.format(nome))
    print('Destino: {}'.format(destino))
    print('Valor do bilhete: R${:.2f}'.format(Quilometro*0.50))
    print('-'*30)
else:
    print('-' * 30)
    print('EXPRESS WORLD')
    print('-' * 30)
    print('Ola, {} Seja bem vindo!'.format(nome))
    print('Destino: {}'.format(destino))
    print('Valor do bilhete: R${:.2f}'.format(Quilometro * 0.45))
    print('-' * 30)